### ISSUE TITLE
Possible defect for class 'RelEnvironment'

### ISSUE THREAD

**Issue by OshinoMoumou** [ekiwi/ekiwi-scons-tools#1]
Greetings!
I noticed that class 'RelEnvironment' referred a StackOverflow post, while [a recent comment](https://stackoverflow.com/questions/8512677/how-to-include-a-template-with-relative-path-in-jinja2#comment83544446_8530761) to it mentioned that this doesn't work on windows because of Jinja issues 411 and 412 - os.path.dirname and os.path.join will use '\\', which FilesystemLoader will reject. Make sure the result is separated with '/' instead of os.path.sep.
I'm trying to learn the usefulness of such small updates on StackOverflow. Would this comment help improve your code? I understand that such defect might not happen in real life situation. In that case, do you think this comment can help prevent future bugs (for example, when the code were reused somewhere else)?
I'll really appreciate it if you could kindly give me some feedback or suggestions. Thank you very much for your time.
Have a nice day!

**Comment by ekiwi** [comment]
Sorry, but I haven't used `scons` or `jinja2` for years. Also, Windows support has always been out of scope.
